# Site settings
title: GitDC | DC的随想录
email: dchan0831@gmail.com
description: DC，一个憧憬诗和远方的「伪」全栈工程师。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gitdc.com" # the base hostname & protocol for your site
author: Derek Chan


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  ID
# weibo:    207124240
github:   gitcdc
# codepen:  username
# dribbble: username

# Comment
disqus_shortname: gitdc


# Google Analytics
google_analytics: UA-73362052-1


# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
